###Clean Prev 1
DELETE {{BASE_URL}}/followers/user10
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

###Clean Prev 1
DELETE {{BASE_URL}}/followers/user11
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

### Crear Followed 1
POST {{BASE_URL}}/followers/user10
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("crear followed 1", function() {
        client.assert(response.status === 201);
    });
%}

### Crear Followed 2
POST {{BASE_URL}}/followers/user11
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("crear followed 2", function() {
        client.assert(response.status === 201);
    });
%}

### Try -> Crear Followed 2
POST {{BASE_URL}}/followers/user11
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("crear followed 2 - Conflict", function() {
        client.assert(response.status === 409);
    });
%}

### Delete Followed 2
DELETE {{BASE_URL}}/followers/user11
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("eliminar followed 2", function() {
        client.assert(response.status === 204);
    });
%}

### Again -> Crear Followed 2
POST {{BASE_URL}}/followers/user11
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("crear nuevamente followed 2", function() {
        client.assert(response.status === 201);
    });
%}

### Get Followed 1
GET  {{BASE_URL}}/followers/user10
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("obtener followed 1", function() {
        client.assert(response.status === 200);
    });
%}

### Get Followers
GET  {{BASE_URL}}/followers
X-User-Id: {{USER_ID}}
Content-Type: application/json
Accept: application/json

> {%
    client.test("obtener followers para user", function() {
        client.assert(response.status === 200);
    });
%}

### Get Followers
GET  {{BASE_URL}}/followers
X-User-Id: user10
Content-Type: application/json
Accept: application/json

> {%
    client.test("obtener followers para user10", function() {
        client.assert(response.status === 200);
    });
%}